import java.util.ArrayList;
import java.util.List;

//How many distinct terms are in the sequence generated by a^b for 2<=a,b<=100
public class Problem29 {
	public static void main(String[] args) {
		long startTime = System.nanoTime();
		int count = 0;
		List<Double> list = new ArrayList<Double>();
		for (int i = 2; i <= 100; i++) {
			for (int j = 2; j <= 100; j++) {
				if (!list.contains(Math.pow(i, j))) {
					list.add(Math.pow(i, j));
					count++;
				}
			}
		}
		System.out.println(count);
		System.out.println((System.nanoTime() - startTime) / 1000000 + "ms");

	}

}
